name: Output Example

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate version
        id: version
        run: echo "version=1.2.3" >> "$GITHUB_OUTPUT"

      - name: Display version
        run: echo "Version is ${{ steps.version.outputs.version }}"